/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * OpenapiOrderBookData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiOrderBookData {
  @SerializedName("algo_id")
  private String algoId = null;

  @SerializedName("algo_ord_no")
  private String algoOrdNo = null;

  @SerializedName("avg_traded_price")
  private BigDecimal avgTradedPrice = null;

  @SerializedName("child_leg_unq_id")
  private Integer childLegUnqId = null;

  @SerializedName("disc_quantity")
  private Integer discQuantity = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("dq_qty_rem")
  private Integer dqQtyRem = null;

  @SerializedName("encash_flag")
  private String encashFlag = null;

  @SerializedName("error_code")
  private String errorCode = null;

  @SerializedName("exch_order_no")
  private String exchOrderNo = null;

  @SerializedName("exch_order_time")
  private String exchOrderTime = null;

  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("exchange_inst_name")
  private String exchangeInstName = null;

  @SerializedName("expiry_date")
  private String expiryDate = null;

  @SerializedName("expiry_flag")
  private String expiryFlag = null;

  @SerializedName("good_till_days_date")
  private String goodTillDaysDate = null;

  @SerializedName("group_id")
  private Integer groupId = null;

  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("instrument")
  private String instrument = null;

  @SerializedName("isin")
  private String isin = null;

  @SerializedName("last_updated_time")
  private String lastUpdatedTime = null;

  @SerializedName("leg_no")
  private Integer legNo = null;

  @SerializedName("lot_size")
  private Integer lotSize = null;

  @SerializedName("mkt_pro_flag")
  private String mktProFlag = null;

  @SerializedName("mkt_pro_value")
  private Integer mktProValue = null;

  @SerializedName("mkt_type")
  private String mktType = null;

  @SerializedName("off_mkt_flag")
  private String offMktFlag = null;

  @SerializedName("opt_type")
  private String optType = null;

  @SerializedName("order_date_time")
  private String orderDateTime = null;

  @SerializedName("order_no")
  private String orderNo = null;

  @SerializedName("order_type")
  private String orderType = null;

  @SerializedName("pan_no")
  private String panNo = null;

  @SerializedName("participant_type")
  private String participantType = null;

  @SerializedName("placed_by")
  private String placedBy = null;

  @SerializedName("pr_abstick_value")
  private Integer prAbstickValue = null;

  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("product_name")
  private String productName = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("reason_description")
  private String reasonDescription = null;

  @SerializedName("ref_ltp")
  private BigDecimal refLtp = null;

  @SerializedName("rem_qty_tot_qty")
  private String remQtyTotQty = null;

  @SerializedName("remaining_quantity")
  private Integer remainingQuantity = null;

  @SerializedName("remarks")
  private String remarks = null;

  @SerializedName("remarks1")
  private String remarks1 = null;

  @SerializedName("remarks2")
  private String remarks2 = null;

  @SerializedName("row_no")
  private Integer rowNo = null;

  @SerializedName("security_id")
  private String securityId = null;

  @SerializedName("segment")
  private String segment = null;

  @SerializedName("serial_no")
  private Integer serialNo = null;

  @SerializedName("series")
  private String series = null;

  @SerializedName("settlor")
  private String settlor = null;

  @SerializedName("sl_abstick_value")
  private Integer slAbstickValue = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("source_name")
  private String sourceName = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("strategy_id")
  private String strategyId = null;

  @SerializedName("strike_price")
  private BigDecimal strikePrice = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("tick_size")
  private Integer tickSize = null;

  @SerializedName("traded_price")
  private BigDecimal tradedPrice = null;

  @SerializedName("traded_qty")
  private Integer tradedQty = null;

  @SerializedName("trailing_sl_value")
  private Integer trailingSlValue = null;

  @SerializedName("trigger_price")
  private BigDecimal triggerPrice = null;

  @SerializedName("txn_type")
  private String txnType = null;

  @SerializedName("validity")
  private String validity = null;

  public OpenapiOrderBookData algoId(String algoId) {
    this.algoId = algoId;
    return this;
  }

   /**
   * Get algoId
   * @return algoId
  **/
  @Schema(description = "")
  public String getAlgoId() {
    return algoId;
  }

  public void setAlgoId(String algoId) {
    this.algoId = algoId;
  }

  public OpenapiOrderBookData algoOrdNo(String algoOrdNo) {
    this.algoOrdNo = algoOrdNo;
    return this;
  }

   /**
   * Get algoOrdNo
   * @return algoOrdNo
  **/
  @Schema(description = "")
  public String getAlgoOrdNo() {
    return algoOrdNo;
  }

  public void setAlgoOrdNo(String algoOrdNo) {
    this.algoOrdNo = algoOrdNo;
  }

  public OpenapiOrderBookData avgTradedPrice(BigDecimal avgTradedPrice) {
    this.avgTradedPrice = avgTradedPrice;
    return this;
  }

   /**
   * Get avgTradedPrice
   * @return avgTradedPrice
  **/
  @Schema(description = "")
  public BigDecimal getAvgTradedPrice() {
    return avgTradedPrice;
  }

  public void setAvgTradedPrice(BigDecimal avgTradedPrice) {
    this.avgTradedPrice = avgTradedPrice;
  }

  public OpenapiOrderBookData childLegUnqId(Integer childLegUnqId) {
    this.childLegUnqId = childLegUnqId;
    return this;
  }

   /**
   * Get childLegUnqId
   * @return childLegUnqId
  **/
  @Schema(description = "")
  public Integer getChildLegUnqId() {
    return childLegUnqId;
  }

  public void setChildLegUnqId(Integer childLegUnqId) {
    this.childLegUnqId = childLegUnqId;
  }

  public OpenapiOrderBookData discQuantity(Integer discQuantity) {
    this.discQuantity = discQuantity;
    return this;
  }

   /**
   * Get discQuantity
   * @return discQuantity
  **/
  @Schema(description = "")
  public Integer getDiscQuantity() {
    return discQuantity;
  }

  public void setDiscQuantity(Integer discQuantity) {
    this.discQuantity = discQuantity;
  }

  public OpenapiOrderBookData displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OpenapiOrderBookData dqQtyRem(Integer dqQtyRem) {
    this.dqQtyRem = dqQtyRem;
    return this;
  }

   /**
   * Get dqQtyRem
   * @return dqQtyRem
  **/
  @Schema(description = "")
  public Integer getDqQtyRem() {
    return dqQtyRem;
  }

  public void setDqQtyRem(Integer dqQtyRem) {
    this.dqQtyRem = dqQtyRem;
  }

  public OpenapiOrderBookData encashFlag(String encashFlag) {
    this.encashFlag = encashFlag;
    return this;
  }

   /**
   * Get encashFlag
   * @return encashFlag
  **/
  @Schema(description = "")
  public String getEncashFlag() {
    return encashFlag;
  }

  public void setEncashFlag(String encashFlag) {
    this.encashFlag = encashFlag;
  }

  public OpenapiOrderBookData errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(description = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public OpenapiOrderBookData exchOrderNo(String exchOrderNo) {
    this.exchOrderNo = exchOrderNo;
    return this;
  }

   /**
   * Get exchOrderNo
   * @return exchOrderNo
  **/
  @Schema(description = "")
  public String getExchOrderNo() {
    return exchOrderNo;
  }

  public void setExchOrderNo(String exchOrderNo) {
    this.exchOrderNo = exchOrderNo;
  }

  public OpenapiOrderBookData exchOrderTime(String exchOrderTime) {
    this.exchOrderTime = exchOrderTime;
    return this;
  }

   /**
   * Get exchOrderTime
   * @return exchOrderTime
  **/
  @Schema(description = "")
  public String getExchOrderTime() {
    return exchOrderTime;
  }

  public void setExchOrderTime(String exchOrderTime) {
    this.exchOrderTime = exchOrderTime;
  }

  public OpenapiOrderBookData exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public OpenapiOrderBookData exchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
    return this;
  }

   /**
   * Get exchangeInstName
   * @return exchangeInstName
  **/
  @Schema(description = "")
  public String getExchangeInstName() {
    return exchangeInstName;
  }

  public void setExchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
  }

  public OpenapiOrderBookData expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(description = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public OpenapiOrderBookData expiryFlag(String expiryFlag) {
    this.expiryFlag = expiryFlag;
    return this;
  }

   /**
   * Get expiryFlag
   * @return expiryFlag
  **/
  @Schema(description = "")
  public String getExpiryFlag() {
    return expiryFlag;
  }

  public void setExpiryFlag(String expiryFlag) {
    this.expiryFlag = expiryFlag;
  }

  public OpenapiOrderBookData goodTillDaysDate(String goodTillDaysDate) {
    this.goodTillDaysDate = goodTillDaysDate;
    return this;
  }

   /**
   * Get goodTillDaysDate
   * @return goodTillDaysDate
  **/
  @Schema(description = "")
  public String getGoodTillDaysDate() {
    return goodTillDaysDate;
  }

  public void setGoodTillDaysDate(String goodTillDaysDate) {
    this.goodTillDaysDate = goodTillDaysDate;
  }

  public OpenapiOrderBookData groupId(Integer groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @Schema(description = "")
  public Integer getGroupId() {
    return groupId;
  }

  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  public OpenapiOrderBookData identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @Schema(description = "")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public OpenapiOrderBookData instrument(String instrument) {
    this.instrument = instrument;
    return this;
  }

   /**
   * Get instrument
   * @return instrument
  **/
  @Schema(description = "")
  public String getInstrument() {
    return instrument;
  }

  public void setInstrument(String instrument) {
    this.instrument = instrument;
  }

  public OpenapiOrderBookData isin(String isin) {
    this.isin = isin;
    return this;
  }

   /**
   * Get isin
   * @return isin
  **/
  @Schema(description = "")
  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public OpenapiOrderBookData lastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
    return this;
  }

   /**
   * Get lastUpdatedTime
   * @return lastUpdatedTime
  **/
  @Schema(description = "")
  public String getLastUpdatedTime() {
    return lastUpdatedTime;
  }

  public void setLastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  public OpenapiOrderBookData legNo(Integer legNo) {
    this.legNo = legNo;
    return this;
  }

   /**
   * Get legNo
   * @return legNo
  **/
  @Schema(description = "")
  public Integer getLegNo() {
    return legNo;
  }

  public void setLegNo(Integer legNo) {
    this.legNo = legNo;
  }

  public OpenapiOrderBookData lotSize(Integer lotSize) {
    this.lotSize = lotSize;
    return this;
  }

   /**
   * Get lotSize
   * @return lotSize
  **/
  @Schema(description = "")
  public Integer getLotSize() {
    return lotSize;
  }

  public void setLotSize(Integer lotSize) {
    this.lotSize = lotSize;
  }

  public OpenapiOrderBookData mktProFlag(String mktProFlag) {
    this.mktProFlag = mktProFlag;
    return this;
  }

   /**
   * Get mktProFlag
   * @return mktProFlag
  **/
  @Schema(description = "")
  public String getMktProFlag() {
    return mktProFlag;
  }

  public void setMktProFlag(String mktProFlag) {
    this.mktProFlag = mktProFlag;
  }

  public OpenapiOrderBookData mktProValue(Integer mktProValue) {
    this.mktProValue = mktProValue;
    return this;
  }

   /**
   * Get mktProValue
   * @return mktProValue
  **/
  @Schema(description = "")
  public Integer getMktProValue() {
    return mktProValue;
  }

  public void setMktProValue(Integer mktProValue) {
    this.mktProValue = mktProValue;
  }

  public OpenapiOrderBookData mktType(String mktType) {
    this.mktType = mktType;
    return this;
  }

   /**
   * Get mktType
   * @return mktType
  **/
  @Schema(description = "")
  public String getMktType() {
    return mktType;
  }

  public void setMktType(String mktType) {
    this.mktType = mktType;
  }

  public OpenapiOrderBookData offMktFlag(String offMktFlag) {
    this.offMktFlag = offMktFlag;
    return this;
  }

   /**
   * Get offMktFlag
   * @return offMktFlag
  **/
  @Schema(description = "")
  public String getOffMktFlag() {
    return offMktFlag;
  }

  public void setOffMktFlag(String offMktFlag) {
    this.offMktFlag = offMktFlag;
  }

  public OpenapiOrderBookData optType(String optType) {
    this.optType = optType;
    return this;
  }

   /**
   * Get optType
   * @return optType
  **/
  @Schema(description = "")
  public String getOptType() {
    return optType;
  }

  public void setOptType(String optType) {
    this.optType = optType;
  }

  public OpenapiOrderBookData orderDateTime(String orderDateTime) {
    this.orderDateTime = orderDateTime;
    return this;
  }

   /**
   * Get orderDateTime
   * @return orderDateTime
  **/
  @Schema(description = "")
  public String getOrderDateTime() {
    return orderDateTime;
  }

  public void setOrderDateTime(String orderDateTime) {
    this.orderDateTime = orderDateTime;
  }

  public OpenapiOrderBookData orderNo(String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

   /**
   * Get orderNo
   * @return orderNo
  **/
  @Schema(description = "")
  public String getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(String orderNo) {
    this.orderNo = orderNo;
  }

  public OpenapiOrderBookData orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @Schema(description = "")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public OpenapiOrderBookData panNo(String panNo) {
    this.panNo = panNo;
    return this;
  }

   /**
   * Get panNo
   * @return panNo
  **/
  @Schema(description = "")
  public String getPanNo() {
    return panNo;
  }

  public void setPanNo(String panNo) {
    this.panNo = panNo;
  }

  public OpenapiOrderBookData participantType(String participantType) {
    this.participantType = participantType;
    return this;
  }

   /**
   * Get participantType
   * @return participantType
  **/
  @Schema(description = "")
  public String getParticipantType() {
    return participantType;
  }

  public void setParticipantType(String participantType) {
    this.participantType = participantType;
  }

  public OpenapiOrderBookData placedBy(String placedBy) {
    this.placedBy = placedBy;
    return this;
  }

   /**
   * Get placedBy
   * @return placedBy
  **/
  @Schema(description = "")
  public String getPlacedBy() {
    return placedBy;
  }

  public void setPlacedBy(String placedBy) {
    this.placedBy = placedBy;
  }

  public OpenapiOrderBookData prAbstickValue(Integer prAbstickValue) {
    this.prAbstickValue = prAbstickValue;
    return this;
  }

   /**
   * Get prAbstickValue
   * @return prAbstickValue
  **/
  @Schema(description = "")
  public Integer getPrAbstickValue() {
    return prAbstickValue;
  }

  public void setPrAbstickValue(Integer prAbstickValue) {
    this.prAbstickValue = prAbstickValue;
  }

  public OpenapiOrderBookData price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public OpenapiOrderBookData product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @Schema(description = "")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public OpenapiOrderBookData productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Get productName
   * @return productName
  **/
  @Schema(description = "")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public OpenapiOrderBookData quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public OpenapiOrderBookData reasonDescription(String reasonDescription) {
    this.reasonDescription = reasonDescription;
    return this;
  }

   /**
   * Get reasonDescription
   * @return reasonDescription
  **/
  @Schema(description = "")
  public String getReasonDescription() {
    return reasonDescription;
  }

  public void setReasonDescription(String reasonDescription) {
    this.reasonDescription = reasonDescription;
  }

  public OpenapiOrderBookData refLtp(BigDecimal refLtp) {
    this.refLtp = refLtp;
    return this;
  }

   /**
   * Get refLtp
   * @return refLtp
  **/
  @Schema(description = "")
  public BigDecimal getRefLtp() {
    return refLtp;
  }

  public void setRefLtp(BigDecimal refLtp) {
    this.refLtp = refLtp;
  }

  public OpenapiOrderBookData remQtyTotQty(String remQtyTotQty) {
    this.remQtyTotQty = remQtyTotQty;
    return this;
  }

   /**
   * Get remQtyTotQty
   * @return remQtyTotQty
  **/
  @Schema(description = "")
  public String getRemQtyTotQty() {
    return remQtyTotQty;
  }

  public void setRemQtyTotQty(String remQtyTotQty) {
    this.remQtyTotQty = remQtyTotQty;
  }

  public OpenapiOrderBookData remainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
    return this;
  }

   /**
   * Get remainingQuantity
   * @return remainingQuantity
  **/
  @Schema(description = "")
  public Integer getRemainingQuantity() {
    return remainingQuantity;
  }

  public void setRemainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
  }

  public OpenapiOrderBookData remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * Get remarks
   * @return remarks
  **/
  @Schema(description = "")
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public OpenapiOrderBookData remarks1(String remarks1) {
    this.remarks1 = remarks1;
    return this;
  }

   /**
   * Get remarks1
   * @return remarks1
  **/
  @Schema(description = "")
  public String getRemarks1() {
    return remarks1;
  }

  public void setRemarks1(String remarks1) {
    this.remarks1 = remarks1;
  }

  public OpenapiOrderBookData remarks2(String remarks2) {
    this.remarks2 = remarks2;
    return this;
  }

   /**
   * Get remarks2
   * @return remarks2
  **/
  @Schema(description = "")
  public String getRemarks2() {
    return remarks2;
  }

  public void setRemarks2(String remarks2) {
    this.remarks2 = remarks2;
  }

  public OpenapiOrderBookData rowNo(Integer rowNo) {
    this.rowNo = rowNo;
    return this;
  }

   /**
   * Get rowNo
   * @return rowNo
  **/
  @Schema(description = "")
  public Integer getRowNo() {
    return rowNo;
  }

  public void setRowNo(Integer rowNo) {
    this.rowNo = rowNo;
  }

  public OpenapiOrderBookData securityId(String securityId) {
    this.securityId = securityId;
    return this;
  }

   /**
   * Get securityId
   * @return securityId
  **/
  @Schema(description = "")
  public String getSecurityId() {
    return securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public OpenapiOrderBookData segment(String segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @Schema(description = "")
  public String getSegment() {
    return segment;
  }

  public void setSegment(String segment) {
    this.segment = segment;
  }

  public OpenapiOrderBookData serialNo(Integer serialNo) {
    this.serialNo = serialNo;
    return this;
  }

   /**
   * Get serialNo
   * @return serialNo
  **/
  @Schema(description = "")
  public Integer getSerialNo() {
    return serialNo;
  }

  public void setSerialNo(Integer serialNo) {
    this.serialNo = serialNo;
  }

  public OpenapiOrderBookData series(String series) {
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @Schema(description = "")
  public String getSeries() {
    return series;
  }

  public void setSeries(String series) {
    this.series = series;
  }

  public OpenapiOrderBookData settlor(String settlor) {
    this.settlor = settlor;
    return this;
  }

   /**
   * Get settlor
   * @return settlor
  **/
  @Schema(description = "")
  public String getSettlor() {
    return settlor;
  }

  public void setSettlor(String settlor) {
    this.settlor = settlor;
  }

  public OpenapiOrderBookData slAbstickValue(Integer slAbstickValue) {
    this.slAbstickValue = slAbstickValue;
    return this;
  }

   /**
   * Get slAbstickValue
   * @return slAbstickValue
  **/
  @Schema(description = "")
  public Integer getSlAbstickValue() {
    return slAbstickValue;
  }

  public void setSlAbstickValue(Integer slAbstickValue) {
    this.slAbstickValue = slAbstickValue;
  }

  public OpenapiOrderBookData source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public OpenapiOrderBookData sourceName(String sourceName) {
    this.sourceName = sourceName;
    return this;
  }

   /**
   * Get sourceName
   * @return sourceName
  **/
  @Schema(description = "")
  public String getSourceName() {
    return sourceName;
  }

  public void setSourceName(String sourceName) {
    this.sourceName = sourceName;
  }

  public OpenapiOrderBookData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public OpenapiOrderBookData strategyId(String strategyId) {
    this.strategyId = strategyId;
    return this;
  }

   /**
   * Get strategyId
   * @return strategyId
  **/
  @Schema(description = "")
  public String getStrategyId() {
    return strategyId;
  }

  public void setStrategyId(String strategyId) {
    this.strategyId = strategyId;
  }

  public OpenapiOrderBookData strikePrice(BigDecimal strikePrice) {
    this.strikePrice = strikePrice;
    return this;
  }

   /**
   * Get strikePrice
   * @return strikePrice
  **/
  @Schema(description = "")
  public BigDecimal getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(BigDecimal strikePrice) {
    this.strikePrice = strikePrice;
  }

  public OpenapiOrderBookData symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public OpenapiOrderBookData tickSize(Integer tickSize) {
    this.tickSize = tickSize;
    return this;
  }

   /**
   * Get tickSize
   * @return tickSize
  **/
  @Schema(description = "")
  public Integer getTickSize() {
    return tickSize;
  }

  public void setTickSize(Integer tickSize) {
    this.tickSize = tickSize;
  }

  public OpenapiOrderBookData tradedPrice(BigDecimal tradedPrice) {
    this.tradedPrice = tradedPrice;
    return this;
  }

   /**
   * Get tradedPrice
   * @return tradedPrice
  **/
  @Schema(description = "")
  public BigDecimal getTradedPrice() {
    return tradedPrice;
  }

  public void setTradedPrice(BigDecimal tradedPrice) {
    this.tradedPrice = tradedPrice;
  }

  public OpenapiOrderBookData tradedQty(Integer tradedQty) {
    this.tradedQty = tradedQty;
    return this;
  }

   /**
   * Get tradedQty
   * @return tradedQty
  **/
  @Schema(description = "")
  public Integer getTradedQty() {
    return tradedQty;
  }

  public void setTradedQty(Integer tradedQty) {
    this.tradedQty = tradedQty;
  }

  public OpenapiOrderBookData trailingSlValue(Integer trailingSlValue) {
    this.trailingSlValue = trailingSlValue;
    return this;
  }

   /**
   * Get trailingSlValue
   * @return trailingSlValue
  **/
  @Schema(description = "")
  public Integer getTrailingSlValue() {
    return trailingSlValue;
  }

  public void setTrailingSlValue(Integer trailingSlValue) {
    this.trailingSlValue = trailingSlValue;
  }

  public OpenapiOrderBookData triggerPrice(BigDecimal triggerPrice) {
    this.triggerPrice = triggerPrice;
    return this;
  }

   /**
   * Get triggerPrice
   * @return triggerPrice
  **/
  @Schema(description = "")
  public BigDecimal getTriggerPrice() {
    return triggerPrice;
  }

  public void setTriggerPrice(BigDecimal triggerPrice) {
    this.triggerPrice = triggerPrice;
  }

  public OpenapiOrderBookData txnType(String txnType) {
    this.txnType = txnType;
    return this;
  }

   /**
   * Get txnType
   * @return txnType
  **/
  @Schema(description = "")
  public String getTxnType() {
    return txnType;
  }

  public void setTxnType(String txnType) {
    this.txnType = txnType;
  }

  public OpenapiOrderBookData validity(String validity) {
    this.validity = validity;
    return this;
  }

   /**
   * Get validity
   * @return validity
  **/
  @Schema(description = "")
  public String getValidity() {
    return validity;
  }

  public void setValidity(String validity) {
    this.validity = validity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiOrderBookData openapiOrderBookData = (OpenapiOrderBookData) o;
    return Objects.equals(this.algoId, openapiOrderBookData.algoId) &&
        Objects.equals(this.algoOrdNo, openapiOrderBookData.algoOrdNo) &&
        Objects.equals(this.avgTradedPrice, openapiOrderBookData.avgTradedPrice) &&
        Objects.equals(this.childLegUnqId, openapiOrderBookData.childLegUnqId) &&
        Objects.equals(this.discQuantity, openapiOrderBookData.discQuantity) &&
        Objects.equals(this.displayName, openapiOrderBookData.displayName) &&
        Objects.equals(this.dqQtyRem, openapiOrderBookData.dqQtyRem) &&
        Objects.equals(this.encashFlag, openapiOrderBookData.encashFlag) &&
        Objects.equals(this.errorCode, openapiOrderBookData.errorCode) &&
        Objects.equals(this.exchOrderNo, openapiOrderBookData.exchOrderNo) &&
        Objects.equals(this.exchOrderTime, openapiOrderBookData.exchOrderTime) &&
        Objects.equals(this.exchange, openapiOrderBookData.exchange) &&
        Objects.equals(this.exchangeInstName, openapiOrderBookData.exchangeInstName) &&
        Objects.equals(this.expiryDate, openapiOrderBookData.expiryDate) &&
        Objects.equals(this.expiryFlag, openapiOrderBookData.expiryFlag) &&
        Objects.equals(this.goodTillDaysDate, openapiOrderBookData.goodTillDaysDate) &&
        Objects.equals(this.groupId, openapiOrderBookData.groupId) &&
        Objects.equals(this.identifier, openapiOrderBookData.identifier) &&
        Objects.equals(this.instrument, openapiOrderBookData.instrument) &&
        Objects.equals(this.isin, openapiOrderBookData.isin) &&
        Objects.equals(this.lastUpdatedTime, openapiOrderBookData.lastUpdatedTime) &&
        Objects.equals(this.legNo, openapiOrderBookData.legNo) &&
        Objects.equals(this.lotSize, openapiOrderBookData.lotSize) &&
        Objects.equals(this.mktProFlag, openapiOrderBookData.mktProFlag) &&
        Objects.equals(this.mktProValue, openapiOrderBookData.mktProValue) &&
        Objects.equals(this.mktType, openapiOrderBookData.mktType) &&
        Objects.equals(this.offMktFlag, openapiOrderBookData.offMktFlag) &&
        Objects.equals(this.optType, openapiOrderBookData.optType) &&
        Objects.equals(this.orderDateTime, openapiOrderBookData.orderDateTime) &&
        Objects.equals(this.orderNo, openapiOrderBookData.orderNo) &&
        Objects.equals(this.orderType, openapiOrderBookData.orderType) &&
        Objects.equals(this.panNo, openapiOrderBookData.panNo) &&
        Objects.equals(this.participantType, openapiOrderBookData.participantType) &&
        Objects.equals(this.placedBy, openapiOrderBookData.placedBy) &&
        Objects.equals(this.prAbstickValue, openapiOrderBookData.prAbstickValue) &&
        Objects.equals(this.price, openapiOrderBookData.price) &&
        Objects.equals(this.product, openapiOrderBookData.product) &&
        Objects.equals(this.productName, openapiOrderBookData.productName) &&
        Objects.equals(this.quantity, openapiOrderBookData.quantity) &&
        Objects.equals(this.reasonDescription, openapiOrderBookData.reasonDescription) &&
        Objects.equals(this.refLtp, openapiOrderBookData.refLtp) &&
        Objects.equals(this.remQtyTotQty, openapiOrderBookData.remQtyTotQty) &&
        Objects.equals(this.remainingQuantity, openapiOrderBookData.remainingQuantity) &&
        Objects.equals(this.remarks, openapiOrderBookData.remarks) &&
        Objects.equals(this.remarks1, openapiOrderBookData.remarks1) &&
        Objects.equals(this.remarks2, openapiOrderBookData.remarks2) &&
        Objects.equals(this.rowNo, openapiOrderBookData.rowNo) &&
        Objects.equals(this.securityId, openapiOrderBookData.securityId) &&
        Objects.equals(this.segment, openapiOrderBookData.segment) &&
        Objects.equals(this.serialNo, openapiOrderBookData.serialNo) &&
        Objects.equals(this.series, openapiOrderBookData.series) &&
        Objects.equals(this.settlor, openapiOrderBookData.settlor) &&
        Objects.equals(this.slAbstickValue, openapiOrderBookData.slAbstickValue) &&
        Objects.equals(this.source, openapiOrderBookData.source) &&
        Objects.equals(this.sourceName, openapiOrderBookData.sourceName) &&
        Objects.equals(this.status, openapiOrderBookData.status) &&
        Objects.equals(this.strategyId, openapiOrderBookData.strategyId) &&
        Objects.equals(this.strikePrice, openapiOrderBookData.strikePrice) &&
        Objects.equals(this.symbol, openapiOrderBookData.symbol) &&
        Objects.equals(this.tickSize, openapiOrderBookData.tickSize) &&
        Objects.equals(this.tradedPrice, openapiOrderBookData.tradedPrice) &&
        Objects.equals(this.tradedQty, openapiOrderBookData.tradedQty) &&
        Objects.equals(this.trailingSlValue, openapiOrderBookData.trailingSlValue) &&
        Objects.equals(this.triggerPrice, openapiOrderBookData.triggerPrice) &&
        Objects.equals(this.txnType, openapiOrderBookData.txnType) &&
        Objects.equals(this.validity, openapiOrderBookData.validity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algoId, algoOrdNo, avgTradedPrice, childLegUnqId, discQuantity, displayName, dqQtyRem, encashFlag, errorCode, exchOrderNo, exchOrderTime, exchange, exchangeInstName, expiryDate, expiryFlag, goodTillDaysDate, groupId, identifier, instrument, isin, lastUpdatedTime, legNo, lotSize, mktProFlag, mktProValue, mktType, offMktFlag, optType, orderDateTime, orderNo, orderType, panNo, participantType, placedBy, prAbstickValue, price, product, productName, quantity, reasonDescription, refLtp, remQtyTotQty, remainingQuantity, remarks, remarks1, remarks2, rowNo, securityId, segment, serialNo, series, settlor, slAbstickValue, source, sourceName, status, strategyId, strikePrice, symbol, tickSize, tradedPrice, tradedQty, trailingSlValue, triggerPrice, txnType, validity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiOrderBookData {\n");
    
    sb.append("    algoId: ").append(toIndentedString(algoId)).append("\n");
    sb.append("    algoOrdNo: ").append(toIndentedString(algoOrdNo)).append("\n");
    sb.append("    avgTradedPrice: ").append(toIndentedString(avgTradedPrice)).append("\n");
    sb.append("    childLegUnqId: ").append(toIndentedString(childLegUnqId)).append("\n");
    sb.append("    discQuantity: ").append(toIndentedString(discQuantity)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dqQtyRem: ").append(toIndentedString(dqQtyRem)).append("\n");
    sb.append("    encashFlag: ").append(toIndentedString(encashFlag)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    exchOrderNo: ").append(toIndentedString(exchOrderNo)).append("\n");
    sb.append("    exchOrderTime: ").append(toIndentedString(exchOrderTime)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeInstName: ").append(toIndentedString(exchangeInstName)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    expiryFlag: ").append(toIndentedString(expiryFlag)).append("\n");
    sb.append("    goodTillDaysDate: ").append(toIndentedString(goodTillDaysDate)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    instrument: ").append(toIndentedString(instrument)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    lastUpdatedTime: ").append(toIndentedString(lastUpdatedTime)).append("\n");
    sb.append("    legNo: ").append(toIndentedString(legNo)).append("\n");
    sb.append("    lotSize: ").append(toIndentedString(lotSize)).append("\n");
    sb.append("    mktProFlag: ").append(toIndentedString(mktProFlag)).append("\n");
    sb.append("    mktProValue: ").append(toIndentedString(mktProValue)).append("\n");
    sb.append("    mktType: ").append(toIndentedString(mktType)).append("\n");
    sb.append("    offMktFlag: ").append(toIndentedString(offMktFlag)).append("\n");
    sb.append("    optType: ").append(toIndentedString(optType)).append("\n");
    sb.append("    orderDateTime: ").append(toIndentedString(orderDateTime)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    panNo: ").append(toIndentedString(panNo)).append("\n");
    sb.append("    participantType: ").append(toIndentedString(participantType)).append("\n");
    sb.append("    placedBy: ").append(toIndentedString(placedBy)).append("\n");
    sb.append("    prAbstickValue: ").append(toIndentedString(prAbstickValue)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    reasonDescription: ").append(toIndentedString(reasonDescription)).append("\n");
    sb.append("    refLtp: ").append(toIndentedString(refLtp)).append("\n");
    sb.append("    remQtyTotQty: ").append(toIndentedString(remQtyTotQty)).append("\n");
    sb.append("    remainingQuantity: ").append(toIndentedString(remainingQuantity)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    remarks1: ").append(toIndentedString(remarks1)).append("\n");
    sb.append("    remarks2: ").append(toIndentedString(remarks2)).append("\n");
    sb.append("    rowNo: ").append(toIndentedString(rowNo)).append("\n");
    sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    serialNo: ").append(toIndentedString(serialNo)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    settlor: ").append(toIndentedString(settlor)).append("\n");
    sb.append("    slAbstickValue: ").append(toIndentedString(slAbstickValue)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceName: ").append(toIndentedString(sourceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    strategyId: ").append(toIndentedString(strategyId)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    tickSize: ").append(toIndentedString(tickSize)).append("\n");
    sb.append("    tradedPrice: ").append(toIndentedString(tradedPrice)).append("\n");
    sb.append("    tradedQty: ").append(toIndentedString(tradedQty)).append("\n");
    sb.append("    trailingSlValue: ").append(toIndentedString(trailingSlValue)).append("\n");
    sb.append("    triggerPrice: ").append(toIndentedString(triggerPrice)).append("\n");
    sb.append("    txnType: ").append(toIndentedString(txnType)).append("\n");
    sb.append("    validity: ").append(toIndentedString(validity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
