/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OpenapiOpenapiConvToDevData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiOpenapiConvToDevData {
  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("mkt_type")
  private String mktType = null;

  @SerializedName("product_from")
  private String productFrom = null;

  @SerializedName("product_to")
  private String productTo = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("security_id")
  private String securityId = null;

  @SerializedName("segment")
  private String segment = null;

  @SerializedName("txn_type")
  private String txnType = null;

  @SerializedName("user_type")
  private String userType = null;

  public OpenapiOpenapiConvToDevData exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public OpenapiOpenapiConvToDevData mktType(String mktType) {
    this.mktType = mktType;
    return this;
  }

   /**
   * Get mktType
   * @return mktType
  **/
  @Schema(description = "")
  public String getMktType() {
    return mktType;
  }

  public void setMktType(String mktType) {
    this.mktType = mktType;
  }

  public OpenapiOpenapiConvToDevData productFrom(String productFrom) {
    this.productFrom = productFrom;
    return this;
  }

   /**
   * Get productFrom
   * @return productFrom
  **/
  @Schema(description = "")
  public String getProductFrom() {
    return productFrom;
  }

  public void setProductFrom(String productFrom) {
    this.productFrom = productFrom;
  }

  public OpenapiOpenapiConvToDevData productTo(String productTo) {
    this.productTo = productTo;
    return this;
  }

   /**
   * Get productTo
   * @return productTo
  **/
  @Schema(description = "")
  public String getProductTo() {
    return productTo;
  }

  public void setProductTo(String productTo) {
    this.productTo = productTo;
  }

  public OpenapiOpenapiConvToDevData quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public OpenapiOpenapiConvToDevData securityId(String securityId) {
    this.securityId = securityId;
    return this;
  }

   /**
   * Get securityId
   * @return securityId
  **/
  @Schema(description = "")
  public String getSecurityId() {
    return securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public OpenapiOpenapiConvToDevData segment(String segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @Schema(description = "")
  public String getSegment() {
    return segment;
  }

  public void setSegment(String segment) {
    this.segment = segment;
  }

  public OpenapiOpenapiConvToDevData txnType(String txnType) {
    this.txnType = txnType;
    return this;
  }

   /**
   * Get txnType
   * @return txnType
  **/
  @Schema(description = "")
  public String getTxnType() {
    return txnType;
  }

  public void setTxnType(String txnType) {
    this.txnType = txnType;
  }

  public OpenapiOpenapiConvToDevData userType(String userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @Schema(description = "")
  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiOpenapiConvToDevData openapiOpenapiConvToDevData = (OpenapiOpenapiConvToDevData) o;
    return Objects.equals(this.exchange, openapiOpenapiConvToDevData.exchange) &&
        Objects.equals(this.mktType, openapiOpenapiConvToDevData.mktType) &&
        Objects.equals(this.productFrom, openapiOpenapiConvToDevData.productFrom) &&
        Objects.equals(this.productTo, openapiOpenapiConvToDevData.productTo) &&
        Objects.equals(this.quantity, openapiOpenapiConvToDevData.quantity) &&
        Objects.equals(this.securityId, openapiOpenapiConvToDevData.securityId) &&
        Objects.equals(this.segment, openapiOpenapiConvToDevData.segment) &&
        Objects.equals(this.txnType, openapiOpenapiConvToDevData.txnType) &&
        Objects.equals(this.userType, openapiOpenapiConvToDevData.userType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exchange, mktType, productFrom, productTo, quantity, securityId, segment, txnType, userType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiOpenapiConvToDevData {\n");
    
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    mktType: ").append(toIndentedString(mktType)).append("\n");
    sb.append("    productFrom: ").append(toIndentedString(productFrom)).append("\n");
    sb.append("    productTo: ").append(toIndentedString(productTo)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    txnType: ").append(toIndentedString(txnType)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
