/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OpenapiOrderDetailData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiOrderDetailData {
  @SerializedName("disc_quantity")
  private Integer discQuantity = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("encash_flag")
  private String encashFlag = null;

  @SerializedName("error_code")
  private String errorCode = null;

  @SerializedName("exch_order_no")
  private String exchOrderNo = null;

  @SerializedName("exch_order_time")
  private String exchOrderTime = null;

  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("exchange_inst_name")
  private String exchangeInstName = null;

  @SerializedName("expiry_date")
  private String expiryDate = null;

  @SerializedName("good_till_days_date")
  private String goodTillDaysDate = null;

  @SerializedName("instrument")
  private String instrument = null;

  @SerializedName("isin")
  private String isin = null;

  @SerializedName("last_updated_time")
  private String lastUpdatedTime = null;

  @SerializedName("lot_size")
  private Integer lotSize = null;

  @SerializedName("mkt_pro_flag")
  private String mktProFlag = null;

  @SerializedName("mkt_pro_value")
  private Integer mktProValue = null;

  @SerializedName("mkt_type")
  private String mktType = null;

  @SerializedName("opt_type")
  private String optType = null;

  @SerializedName("order_date_time")
  private String orderDateTime = null;

  @SerializedName("order_no")
  private String orderNo = null;

  @SerializedName("order_type")
  private String orderType = null;

  @SerializedName("pan_no")
  private String panNo = null;

  @SerializedName("participant_type")
  private String participantType = null;

  @SerializedName("price")
  private Integer price = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("product_name")
  private String productName = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("reason_description")
  private String reasonDescription = null;

  @SerializedName("remaining_quantity")
  private Integer remainingQuantity = null;

  @SerializedName("security_id")
  private String securityId = null;

  @SerializedName("serial_no")
  private Integer serialNo = null;

  @SerializedName("series")
  private String series = null;

  @SerializedName("settlor")
  private String settlor = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("source_name")
  private String sourceName = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("strike_price")
  private Integer strikePrice = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("traded_quantity")
  private Integer tradedQuantity = null;

  @SerializedName("trigger_price")
  private Integer triggerPrice = null;

  @SerializedName("txn_type")
  private String txnType = null;

  @SerializedName("validity")
  private String validity = null;

  public OpenapiOrderDetailData discQuantity(Integer discQuantity) {
    this.discQuantity = discQuantity;
    return this;
  }

   /**
   * Get discQuantity
   * @return discQuantity
  **/
  @Schema(description = "")
  public Integer getDiscQuantity() {
    return discQuantity;
  }

  public void setDiscQuantity(Integer discQuantity) {
    this.discQuantity = discQuantity;
  }

  public OpenapiOrderDetailData displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OpenapiOrderDetailData encashFlag(String encashFlag) {
    this.encashFlag = encashFlag;
    return this;
  }

   /**
   * Get encashFlag
   * @return encashFlag
  **/
  @Schema(description = "")
  public String getEncashFlag() {
    return encashFlag;
  }

  public void setEncashFlag(String encashFlag) {
    this.encashFlag = encashFlag;
  }

  public OpenapiOrderDetailData errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(description = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public OpenapiOrderDetailData exchOrderNo(String exchOrderNo) {
    this.exchOrderNo = exchOrderNo;
    return this;
  }

   /**
   * Get exchOrderNo
   * @return exchOrderNo
  **/
  @Schema(description = "")
  public String getExchOrderNo() {
    return exchOrderNo;
  }

  public void setExchOrderNo(String exchOrderNo) {
    this.exchOrderNo = exchOrderNo;
  }

  public OpenapiOrderDetailData exchOrderTime(String exchOrderTime) {
    this.exchOrderTime = exchOrderTime;
    return this;
  }

   /**
   * Get exchOrderTime
   * @return exchOrderTime
  **/
  @Schema(description = "")
  public String getExchOrderTime() {
    return exchOrderTime;
  }

  public void setExchOrderTime(String exchOrderTime) {
    this.exchOrderTime = exchOrderTime;
  }

  public OpenapiOrderDetailData exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public OpenapiOrderDetailData exchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
    return this;
  }

   /**
   * Get exchangeInstName
   * @return exchangeInstName
  **/
  @Schema(description = "")
  public String getExchangeInstName() {
    return exchangeInstName;
  }

  public void setExchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
  }

  public OpenapiOrderDetailData expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(description = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public OpenapiOrderDetailData goodTillDaysDate(String goodTillDaysDate) {
    this.goodTillDaysDate = goodTillDaysDate;
    return this;
  }

   /**
   * Get goodTillDaysDate
   * @return goodTillDaysDate
  **/
  @Schema(description = "")
  public String getGoodTillDaysDate() {
    return goodTillDaysDate;
  }

  public void setGoodTillDaysDate(String goodTillDaysDate) {
    this.goodTillDaysDate = goodTillDaysDate;
  }

  public OpenapiOrderDetailData instrument(String instrument) {
    this.instrument = instrument;
    return this;
  }

   /**
   * Get instrument
   * @return instrument
  **/
  @Schema(description = "")
  public String getInstrument() {
    return instrument;
  }

  public void setInstrument(String instrument) {
    this.instrument = instrument;
  }

  public OpenapiOrderDetailData isin(String isin) {
    this.isin = isin;
    return this;
  }

   /**
   * Get isin
   * @return isin
  **/
  @Schema(description = "")
  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public OpenapiOrderDetailData lastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
    return this;
  }

   /**
   * Get lastUpdatedTime
   * @return lastUpdatedTime
  **/
  @Schema(description = "")
  public String getLastUpdatedTime() {
    return lastUpdatedTime;
  }

  public void setLastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  public OpenapiOrderDetailData lotSize(Integer lotSize) {
    this.lotSize = lotSize;
    return this;
  }

   /**
   * Get lotSize
   * @return lotSize
  **/
  @Schema(description = "")
  public Integer getLotSize() {
    return lotSize;
  }

  public void setLotSize(Integer lotSize) {
    this.lotSize = lotSize;
  }

  public OpenapiOrderDetailData mktProFlag(String mktProFlag) {
    this.mktProFlag = mktProFlag;
    return this;
  }

   /**
   * Get mktProFlag
   * @return mktProFlag
  **/
  @Schema(description = "")
  public String getMktProFlag() {
    return mktProFlag;
  }

  public void setMktProFlag(String mktProFlag) {
    this.mktProFlag = mktProFlag;
  }

  public OpenapiOrderDetailData mktProValue(Integer mktProValue) {
    this.mktProValue = mktProValue;
    return this;
  }

   /**
   * Get mktProValue
   * @return mktProValue
  **/
  @Schema(description = "")
  public Integer getMktProValue() {
    return mktProValue;
  }

  public void setMktProValue(Integer mktProValue) {
    this.mktProValue = mktProValue;
  }

  public OpenapiOrderDetailData mktType(String mktType) {
    this.mktType = mktType;
    return this;
  }

   /**
   * Get mktType
   * @return mktType
  **/
  @Schema(description = "")
  public String getMktType() {
    return mktType;
  }

  public void setMktType(String mktType) {
    this.mktType = mktType;
  }

  public OpenapiOrderDetailData optType(String optType) {
    this.optType = optType;
    return this;
  }

   /**
   * Get optType
   * @return optType
  **/
  @Schema(description = "")
  public String getOptType() {
    return optType;
  }

  public void setOptType(String optType) {
    this.optType = optType;
  }

  public OpenapiOrderDetailData orderDateTime(String orderDateTime) {
    this.orderDateTime = orderDateTime;
    return this;
  }

   /**
   * Get orderDateTime
   * @return orderDateTime
  **/
  @Schema(description = "")
  public String getOrderDateTime() {
    return orderDateTime;
  }

  public void setOrderDateTime(String orderDateTime) {
    this.orderDateTime = orderDateTime;
  }

  public OpenapiOrderDetailData orderNo(String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

   /**
   * Get orderNo
   * @return orderNo
  **/
  @Schema(description = "")
  public String getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(String orderNo) {
    this.orderNo = orderNo;
  }

  public OpenapiOrderDetailData orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @Schema(description = "")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public OpenapiOrderDetailData panNo(String panNo) {
    this.panNo = panNo;
    return this;
  }

   /**
   * Get panNo
   * @return panNo
  **/
  @Schema(description = "")
  public String getPanNo() {
    return panNo;
  }

  public void setPanNo(String panNo) {
    this.panNo = panNo;
  }

  public OpenapiOrderDetailData participantType(String participantType) {
    this.participantType = participantType;
    return this;
  }

   /**
   * Get participantType
   * @return participantType
  **/
  @Schema(description = "")
  public String getParticipantType() {
    return participantType;
  }

  public void setParticipantType(String participantType) {
    this.participantType = participantType;
  }

  public OpenapiOrderDetailData price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public OpenapiOrderDetailData product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @Schema(description = "")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public OpenapiOrderDetailData productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Get productName
   * @return productName
  **/
  @Schema(description = "")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public OpenapiOrderDetailData quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public OpenapiOrderDetailData reasonDescription(String reasonDescription) {
    this.reasonDescription = reasonDescription;
    return this;
  }

   /**
   * Get reasonDescription
   * @return reasonDescription
  **/
  @Schema(description = "")
  public String getReasonDescription() {
    return reasonDescription;
  }

  public void setReasonDescription(String reasonDescription) {
    this.reasonDescription = reasonDescription;
  }

  public OpenapiOrderDetailData remainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
    return this;
  }

   /**
   * Get remainingQuantity
   * @return remainingQuantity
  **/
  @Schema(description = "")
  public Integer getRemainingQuantity() {
    return remainingQuantity;
  }

  public void setRemainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
  }

  public OpenapiOrderDetailData securityId(String securityId) {
    this.securityId = securityId;
    return this;
  }

   /**
   * Get securityId
   * @return securityId
  **/
  @Schema(description = "")
  public String getSecurityId() {
    return securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public OpenapiOrderDetailData serialNo(Integer serialNo) {
    this.serialNo = serialNo;
    return this;
  }

   /**
   * Get serialNo
   * @return serialNo
  **/
  @Schema(description = "")
  public Integer getSerialNo() {
    return serialNo;
  }

  public void setSerialNo(Integer serialNo) {
    this.serialNo = serialNo;
  }

  public OpenapiOrderDetailData series(String series) {
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @Schema(description = "")
  public String getSeries() {
    return series;
  }

  public void setSeries(String series) {
    this.series = series;
  }

  public OpenapiOrderDetailData settlor(String settlor) {
    this.settlor = settlor;
    return this;
  }

   /**
   * Get settlor
   * @return settlor
  **/
  @Schema(description = "")
  public String getSettlor() {
    return settlor;
  }

  public void setSettlor(String settlor) {
    this.settlor = settlor;
  }

  public OpenapiOrderDetailData source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public OpenapiOrderDetailData sourceName(String sourceName) {
    this.sourceName = sourceName;
    return this;
  }

   /**
   * Get sourceName
   * @return sourceName
  **/
  @Schema(description = "")
  public String getSourceName() {
    return sourceName;
  }

  public void setSourceName(String sourceName) {
    this.sourceName = sourceName;
  }

  public OpenapiOrderDetailData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public OpenapiOrderDetailData strikePrice(Integer strikePrice) {
    this.strikePrice = strikePrice;
    return this;
  }

   /**
   * Get strikePrice
   * @return strikePrice
  **/
  @Schema(description = "")
  public Integer getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(Integer strikePrice) {
    this.strikePrice = strikePrice;
  }

  public OpenapiOrderDetailData symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public OpenapiOrderDetailData tradedQuantity(Integer tradedQuantity) {
    this.tradedQuantity = tradedQuantity;
    return this;
  }

   /**
   * Get tradedQuantity
   * @return tradedQuantity
  **/
  @Schema(description = "")
  public Integer getTradedQuantity() {
    return tradedQuantity;
  }

  public void setTradedQuantity(Integer tradedQuantity) {
    this.tradedQuantity = tradedQuantity;
  }

  public OpenapiOrderDetailData triggerPrice(Integer triggerPrice) {
    this.triggerPrice = triggerPrice;
    return this;
  }

   /**
   * Get triggerPrice
   * @return triggerPrice
  **/
  @Schema(description = "")
  public Integer getTriggerPrice() {
    return triggerPrice;
  }

  public void setTriggerPrice(Integer triggerPrice) {
    this.triggerPrice = triggerPrice;
  }

  public OpenapiOrderDetailData txnType(String txnType) {
    this.txnType = txnType;
    return this;
  }

   /**
   * Get txnType
   * @return txnType
  **/
  @Schema(description = "")
  public String getTxnType() {
    return txnType;
  }

  public void setTxnType(String txnType) {
    this.txnType = txnType;
  }

  public OpenapiOrderDetailData validity(String validity) {
    this.validity = validity;
    return this;
  }

   /**
   * Get validity
   * @return validity
  **/
  @Schema(description = "")
  public String getValidity() {
    return validity;
  }

  public void setValidity(String validity) {
    this.validity = validity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiOrderDetailData openapiOrderDetailData = (OpenapiOrderDetailData) o;
    return Objects.equals(this.discQuantity, openapiOrderDetailData.discQuantity) &&
        Objects.equals(this.displayName, openapiOrderDetailData.displayName) &&
        Objects.equals(this.encashFlag, openapiOrderDetailData.encashFlag) &&
        Objects.equals(this.errorCode, openapiOrderDetailData.errorCode) &&
        Objects.equals(this.exchOrderNo, openapiOrderDetailData.exchOrderNo) &&
        Objects.equals(this.exchOrderTime, openapiOrderDetailData.exchOrderTime) &&
        Objects.equals(this.exchange, openapiOrderDetailData.exchange) &&
        Objects.equals(this.exchangeInstName, openapiOrderDetailData.exchangeInstName) &&
        Objects.equals(this.expiryDate, openapiOrderDetailData.expiryDate) &&
        Objects.equals(this.goodTillDaysDate, openapiOrderDetailData.goodTillDaysDate) &&
        Objects.equals(this.instrument, openapiOrderDetailData.instrument) &&
        Objects.equals(this.isin, openapiOrderDetailData.isin) &&
        Objects.equals(this.lastUpdatedTime, openapiOrderDetailData.lastUpdatedTime) &&
        Objects.equals(this.lotSize, openapiOrderDetailData.lotSize) &&
        Objects.equals(this.mktProFlag, openapiOrderDetailData.mktProFlag) &&
        Objects.equals(this.mktProValue, openapiOrderDetailData.mktProValue) &&
        Objects.equals(this.mktType, openapiOrderDetailData.mktType) &&
        Objects.equals(this.optType, openapiOrderDetailData.optType) &&
        Objects.equals(this.orderDateTime, openapiOrderDetailData.orderDateTime) &&
        Objects.equals(this.orderNo, openapiOrderDetailData.orderNo) &&
        Objects.equals(this.orderType, openapiOrderDetailData.orderType) &&
        Objects.equals(this.panNo, openapiOrderDetailData.panNo) &&
        Objects.equals(this.participantType, openapiOrderDetailData.participantType) &&
        Objects.equals(this.price, openapiOrderDetailData.price) &&
        Objects.equals(this.product, openapiOrderDetailData.product) &&
        Objects.equals(this.productName, openapiOrderDetailData.productName) &&
        Objects.equals(this.quantity, openapiOrderDetailData.quantity) &&
        Objects.equals(this.reasonDescription, openapiOrderDetailData.reasonDescription) &&
        Objects.equals(this.remainingQuantity, openapiOrderDetailData.remainingQuantity) &&
        Objects.equals(this.securityId, openapiOrderDetailData.securityId) &&
        Objects.equals(this.serialNo, openapiOrderDetailData.serialNo) &&
        Objects.equals(this.series, openapiOrderDetailData.series) &&
        Objects.equals(this.settlor, openapiOrderDetailData.settlor) &&
        Objects.equals(this.source, openapiOrderDetailData.source) &&
        Objects.equals(this.sourceName, openapiOrderDetailData.sourceName) &&
        Objects.equals(this.status, openapiOrderDetailData.status) &&
        Objects.equals(this.strikePrice, openapiOrderDetailData.strikePrice) &&
        Objects.equals(this.symbol, openapiOrderDetailData.symbol) &&
        Objects.equals(this.tradedQuantity, openapiOrderDetailData.tradedQuantity) &&
        Objects.equals(this.triggerPrice, openapiOrderDetailData.triggerPrice) &&
        Objects.equals(this.txnType, openapiOrderDetailData.txnType) &&
        Objects.equals(this.validity, openapiOrderDetailData.validity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discQuantity, displayName, encashFlag, errorCode, exchOrderNo, exchOrderTime, exchange, exchangeInstName, expiryDate, goodTillDaysDate, instrument, isin, lastUpdatedTime, lotSize, mktProFlag, mktProValue, mktType, optType, orderDateTime, orderNo, orderType, panNo, participantType, price, product, productName, quantity, reasonDescription, remainingQuantity, securityId, serialNo, series, settlor, source, sourceName, status, strikePrice, symbol, tradedQuantity, triggerPrice, txnType, validity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiOrderDetailData {\n");
    
    sb.append("    discQuantity: ").append(toIndentedString(discQuantity)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    encashFlag: ").append(toIndentedString(encashFlag)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    exchOrderNo: ").append(toIndentedString(exchOrderNo)).append("\n");
    sb.append("    exchOrderTime: ").append(toIndentedString(exchOrderTime)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeInstName: ").append(toIndentedString(exchangeInstName)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    goodTillDaysDate: ").append(toIndentedString(goodTillDaysDate)).append("\n");
    sb.append("    instrument: ").append(toIndentedString(instrument)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    lastUpdatedTime: ").append(toIndentedString(lastUpdatedTime)).append("\n");
    sb.append("    lotSize: ").append(toIndentedString(lotSize)).append("\n");
    sb.append("    mktProFlag: ").append(toIndentedString(mktProFlag)).append("\n");
    sb.append("    mktProValue: ").append(toIndentedString(mktProValue)).append("\n");
    sb.append("    mktType: ").append(toIndentedString(mktType)).append("\n");
    sb.append("    optType: ").append(toIndentedString(optType)).append("\n");
    sb.append("    orderDateTime: ").append(toIndentedString(orderDateTime)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    panNo: ").append(toIndentedString(panNo)).append("\n");
    sb.append("    participantType: ").append(toIndentedString(participantType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    reasonDescription: ").append(toIndentedString(reasonDescription)).append("\n");
    sb.append("    remainingQuantity: ").append(toIndentedString(remainingQuantity)).append("\n");
    sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
    sb.append("    serialNo: ").append(toIndentedString(serialNo)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    settlor: ").append(toIndentedString(settlor)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceName: ").append(toIndentedString(sourceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    tradedQuantity: ").append(toIndentedString(tradedQuantity)).append("\n");
    sb.append("    triggerPrice: ").append(toIndentedString(triggerPrice)).append("\n");
    sb.append("    txnType: ").append(toIndentedString(txnType)).append("\n");
    sb.append("    validity: ").append(toIndentedString(validity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
