/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * OpenapiHoldingDetailsData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiHoldingDetailsData {
  @SerializedName("bse_security_id")
  private String bseSecurityId = null;

  @SerializedName("bse_symbol")
  private String bseSymbol = null;

  @SerializedName("bse_tick_size")
  private Integer bseTickSize = null;

  @SerializedName("cagr")
  private BigDecimal cagr = null;

  @SerializedName("collateral")
  private BigDecimal collateral = null;

  @SerializedName("collateral_perc")
  private BigDecimal collateralPerc = null;

  @SerializedName("collateral_qty")
  private BigDecimal collateralQty = null;

  @SerializedName("collateral_qty_com")
  private BigDecimal collateralQtyCom = null;

  @SerializedName("collateral_qty_cur")
  private BigDecimal collateralQtyCur = null;

  @SerializedName("collateral_qty_drv")
  private BigDecimal collateralQtyDrv = null;

  @SerializedName("com_collateral")
  private BigDecimal comCollateral = null;

  @SerializedName("cost_price")
  private BigDecimal costPrice = null;

  @SerializedName("cur_collateral")
  private BigDecimal curCollateral = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("drv_collateral")
  private BigDecimal drvCollateral = null;

  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("exchange_inst_name")
  private String exchangeInstName = null;

  @SerializedName("isin_code")
  private String isinCode = null;

  @SerializedName("last_traded_price")
  private BigDecimal lastTradedPrice = null;

  @SerializedName("market_value")
  private BigDecimal marketValue = null;

  @SerializedName("nse_security_id")
  private String nseSecurityId = null;

  @SerializedName("nse_symbol")
  private String nseSymbol = null;

  @SerializedName("nse_tick_size")
  private Integer nseTickSize = null;

  @SerializedName("pledge_qty")
  private BigDecimal pledgeQty = null;

  @SerializedName("previous_close_price")
  private BigDecimal previousClosePrice = null;

  @SerializedName("quantity")
  private BigDecimal quantity = null;

  @SerializedName("remaining_quantity")
  private BigDecimal remainingQuantity = null;

  @SerializedName("row_no")
  private Integer rowNo = null;

  @SerializedName("security_source_type")
  private String securitySourceType = null;

  @SerializedName("total_quantity")
  private BigDecimal totalQuantity = null;

  @SerializedName("utilized_quantity")
  private BigDecimal utilizedQuantity = null;

  @SerializedName("xirr")
  private BigDecimal xirr = null;

  public OpenapiHoldingDetailsData bseSecurityId(String bseSecurityId) {
    this.bseSecurityId = bseSecurityId;
    return this;
  }

   /**
   * Get bseSecurityId
   * @return bseSecurityId
  **/
  @Schema(description = "")
  public String getBseSecurityId() {
    return bseSecurityId;
  }

  public void setBseSecurityId(String bseSecurityId) {
    this.bseSecurityId = bseSecurityId;
  }

  public OpenapiHoldingDetailsData bseSymbol(String bseSymbol) {
    this.bseSymbol = bseSymbol;
    return this;
  }

   /**
   * Get bseSymbol
   * @return bseSymbol
  **/
  @Schema(description = "")
  public String getBseSymbol() {
    return bseSymbol;
  }

  public void setBseSymbol(String bseSymbol) {
    this.bseSymbol = bseSymbol;
  }

  public OpenapiHoldingDetailsData bseTickSize(Integer bseTickSize) {
    this.bseTickSize = bseTickSize;
    return this;
  }

   /**
   * Get bseTickSize
   * @return bseTickSize
  **/
  @Schema(description = "")
  public Integer getBseTickSize() {
    return bseTickSize;
  }

  public void setBseTickSize(Integer bseTickSize) {
    this.bseTickSize = bseTickSize;
  }

  public OpenapiHoldingDetailsData cagr(BigDecimal cagr) {
    this.cagr = cagr;
    return this;
  }

   /**
   * Get cagr
   * @return cagr
  **/
  @Schema(description = "")
  public BigDecimal getCagr() {
    return cagr;
  }

  public void setCagr(BigDecimal cagr) {
    this.cagr = cagr;
  }

  public OpenapiHoldingDetailsData collateral(BigDecimal collateral) {
    this.collateral = collateral;
    return this;
  }

   /**
   * Get collateral
   * @return collateral
  **/
  @Schema(description = "")
  public BigDecimal getCollateral() {
    return collateral;
  }

  public void setCollateral(BigDecimal collateral) {
    this.collateral = collateral;
  }

  public OpenapiHoldingDetailsData collateralPerc(BigDecimal collateralPerc) {
    this.collateralPerc = collateralPerc;
    return this;
  }

   /**
   * Get collateralPerc
   * @return collateralPerc
  **/
  @Schema(description = "")
  public BigDecimal getCollateralPerc() {
    return collateralPerc;
  }

  public void setCollateralPerc(BigDecimal collateralPerc) {
    this.collateralPerc = collateralPerc;
  }

  public OpenapiHoldingDetailsData collateralQty(BigDecimal collateralQty) {
    this.collateralQty = collateralQty;
    return this;
  }

   /**
   * Get collateralQty
   * @return collateralQty
  **/
  @Schema(description = "")
  public BigDecimal getCollateralQty() {
    return collateralQty;
  }

  public void setCollateralQty(BigDecimal collateralQty) {
    this.collateralQty = collateralQty;
  }

  public OpenapiHoldingDetailsData collateralQtyCom(BigDecimal collateralQtyCom) {
    this.collateralQtyCom = collateralQtyCom;
    return this;
  }

   /**
   * Get collateralQtyCom
   * @return collateralQtyCom
  **/
  @Schema(description = "")
  public BigDecimal getCollateralQtyCom() {
    return collateralQtyCom;
  }

  public void setCollateralQtyCom(BigDecimal collateralQtyCom) {
    this.collateralQtyCom = collateralQtyCom;
  }

  public OpenapiHoldingDetailsData collateralQtyCur(BigDecimal collateralQtyCur) {
    this.collateralQtyCur = collateralQtyCur;
    return this;
  }

   /**
   * Get collateralQtyCur
   * @return collateralQtyCur
  **/
  @Schema(description = "")
  public BigDecimal getCollateralQtyCur() {
    return collateralQtyCur;
  }

  public void setCollateralQtyCur(BigDecimal collateralQtyCur) {
    this.collateralQtyCur = collateralQtyCur;
  }

  public OpenapiHoldingDetailsData collateralQtyDrv(BigDecimal collateralQtyDrv) {
    this.collateralQtyDrv = collateralQtyDrv;
    return this;
  }

   /**
   * Get collateralQtyDrv
   * @return collateralQtyDrv
  **/
  @Schema(description = "")
  public BigDecimal getCollateralQtyDrv() {
    return collateralQtyDrv;
  }

  public void setCollateralQtyDrv(BigDecimal collateralQtyDrv) {
    this.collateralQtyDrv = collateralQtyDrv;
  }

  public OpenapiHoldingDetailsData comCollateral(BigDecimal comCollateral) {
    this.comCollateral = comCollateral;
    return this;
  }

   /**
   * Get comCollateral
   * @return comCollateral
  **/
  @Schema(description = "")
  public BigDecimal getComCollateral() {
    return comCollateral;
  }

  public void setComCollateral(BigDecimal comCollateral) {
    this.comCollateral = comCollateral;
  }

  public OpenapiHoldingDetailsData costPrice(BigDecimal costPrice) {
    this.costPrice = costPrice;
    return this;
  }

   /**
   * Get costPrice
   * @return costPrice
  **/
  @Schema(description = "")
  public BigDecimal getCostPrice() {
    return costPrice;
  }

  public void setCostPrice(BigDecimal costPrice) {
    this.costPrice = costPrice;
  }

  public OpenapiHoldingDetailsData curCollateral(BigDecimal curCollateral) {
    this.curCollateral = curCollateral;
    return this;
  }

   /**
   * Get curCollateral
   * @return curCollateral
  **/
  @Schema(description = "")
  public BigDecimal getCurCollateral() {
    return curCollateral;
  }

  public void setCurCollateral(BigDecimal curCollateral) {
    this.curCollateral = curCollateral;
  }

  public OpenapiHoldingDetailsData displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OpenapiHoldingDetailsData drvCollateral(BigDecimal drvCollateral) {
    this.drvCollateral = drvCollateral;
    return this;
  }

   /**
   * Get drvCollateral
   * @return drvCollateral
  **/
  @Schema(description = "")
  public BigDecimal getDrvCollateral() {
    return drvCollateral;
  }

  public void setDrvCollateral(BigDecimal drvCollateral) {
    this.drvCollateral = drvCollateral;
  }

  public OpenapiHoldingDetailsData exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public OpenapiHoldingDetailsData exchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
    return this;
  }

   /**
   * Get exchangeInstName
   * @return exchangeInstName
  **/
  @Schema(description = "")
  public String getExchangeInstName() {
    return exchangeInstName;
  }

  public void setExchangeInstName(String exchangeInstName) {
    this.exchangeInstName = exchangeInstName;
  }

  public OpenapiHoldingDetailsData isinCode(String isinCode) {
    this.isinCode = isinCode;
    return this;
  }

   /**
   * Get isinCode
   * @return isinCode
  **/
  @Schema(description = "")
  public String getIsinCode() {
    return isinCode;
  }

  public void setIsinCode(String isinCode) {
    this.isinCode = isinCode;
  }

  public OpenapiHoldingDetailsData lastTradedPrice(BigDecimal lastTradedPrice) {
    this.lastTradedPrice = lastTradedPrice;
    return this;
  }

   /**
   * Get lastTradedPrice
   * @return lastTradedPrice
  **/
  @Schema(description = "")
  public BigDecimal getLastTradedPrice() {
    return lastTradedPrice;
  }

  public void setLastTradedPrice(BigDecimal lastTradedPrice) {
    this.lastTradedPrice = lastTradedPrice;
  }

  public OpenapiHoldingDetailsData marketValue(BigDecimal marketValue) {
    this.marketValue = marketValue;
    return this;
  }

   /**
   * Get marketValue
   * @return marketValue
  **/
  @Schema(description = "")
  public BigDecimal getMarketValue() {
    return marketValue;
  }

  public void setMarketValue(BigDecimal marketValue) {
    this.marketValue = marketValue;
  }

  public OpenapiHoldingDetailsData nseSecurityId(String nseSecurityId) {
    this.nseSecurityId = nseSecurityId;
    return this;
  }

   /**
   * Get nseSecurityId
   * @return nseSecurityId
  **/
  @Schema(description = "")
  public String getNseSecurityId() {
    return nseSecurityId;
  }

  public void setNseSecurityId(String nseSecurityId) {
    this.nseSecurityId = nseSecurityId;
  }

  public OpenapiHoldingDetailsData nseSymbol(String nseSymbol) {
    this.nseSymbol = nseSymbol;
    return this;
  }

   /**
   * Get nseSymbol
   * @return nseSymbol
  **/
  @Schema(description = "")
  public String getNseSymbol() {
    return nseSymbol;
  }

  public void setNseSymbol(String nseSymbol) {
    this.nseSymbol = nseSymbol;
  }

  public OpenapiHoldingDetailsData nseTickSize(Integer nseTickSize) {
    this.nseTickSize = nseTickSize;
    return this;
  }

   /**
   * Get nseTickSize
   * @return nseTickSize
  **/
  @Schema(description = "")
  public Integer getNseTickSize() {
    return nseTickSize;
  }

  public void setNseTickSize(Integer nseTickSize) {
    this.nseTickSize = nseTickSize;
  }

  public OpenapiHoldingDetailsData pledgeQty(BigDecimal pledgeQty) {
    this.pledgeQty = pledgeQty;
    return this;
  }

   /**
   * Get pledgeQty
   * @return pledgeQty
  **/
  @Schema(description = "")
  public BigDecimal getPledgeQty() {
    return pledgeQty;
  }

  public void setPledgeQty(BigDecimal pledgeQty) {
    this.pledgeQty = pledgeQty;
  }

  public OpenapiHoldingDetailsData previousClosePrice(BigDecimal previousClosePrice) {
    this.previousClosePrice = previousClosePrice;
    return this;
  }

   /**
   * Get previousClosePrice
   * @return previousClosePrice
  **/
  @Schema(description = "")
  public BigDecimal getPreviousClosePrice() {
    return previousClosePrice;
  }

  public void setPreviousClosePrice(BigDecimal previousClosePrice) {
    this.previousClosePrice = previousClosePrice;
  }

  public OpenapiHoldingDetailsData quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public OpenapiHoldingDetailsData remainingQuantity(BigDecimal remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
    return this;
  }

   /**
   * Get remainingQuantity
   * @return remainingQuantity
  **/
  @Schema(description = "")
  public BigDecimal getRemainingQuantity() {
    return remainingQuantity;
  }

  public void setRemainingQuantity(BigDecimal remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
  }

  public OpenapiHoldingDetailsData rowNo(Integer rowNo) {
    this.rowNo = rowNo;
    return this;
  }

   /**
   * Get rowNo
   * @return rowNo
  **/
  @Schema(description = "")
  public Integer getRowNo() {
    return rowNo;
  }

  public void setRowNo(Integer rowNo) {
    this.rowNo = rowNo;
  }

  public OpenapiHoldingDetailsData securitySourceType(String securitySourceType) {
    this.securitySourceType = securitySourceType;
    return this;
  }

   /**
   * Get securitySourceType
   * @return securitySourceType
  **/
  @Schema(description = "")
  public String getSecuritySourceType() {
    return securitySourceType;
  }

  public void setSecuritySourceType(String securitySourceType) {
    this.securitySourceType = securitySourceType;
  }

  public OpenapiHoldingDetailsData totalQuantity(BigDecimal totalQuantity) {
    this.totalQuantity = totalQuantity;
    return this;
  }

   /**
   * Get totalQuantity
   * @return totalQuantity
  **/
  @Schema(description = "")
  public BigDecimal getTotalQuantity() {
    return totalQuantity;
  }

  public void setTotalQuantity(BigDecimal totalQuantity) {
    this.totalQuantity = totalQuantity;
  }

  public OpenapiHoldingDetailsData utilizedQuantity(BigDecimal utilizedQuantity) {
    this.utilizedQuantity = utilizedQuantity;
    return this;
  }

   /**
   * Get utilizedQuantity
   * @return utilizedQuantity
  **/
  @Schema(description = "")
  public BigDecimal getUtilizedQuantity() {
    return utilizedQuantity;
  }

  public void setUtilizedQuantity(BigDecimal utilizedQuantity) {
    this.utilizedQuantity = utilizedQuantity;
  }

  public OpenapiHoldingDetailsData xirr(BigDecimal xirr) {
    this.xirr = xirr;
    return this;
  }

   /**
   * Get xirr
   * @return xirr
  **/
  @Schema(description = "")
  public BigDecimal getXirr() {
    return xirr;
  }

  public void setXirr(BigDecimal xirr) {
    this.xirr = xirr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiHoldingDetailsData openapiHoldingDetailsData = (OpenapiHoldingDetailsData) o;
    return Objects.equals(this.bseSecurityId, openapiHoldingDetailsData.bseSecurityId) &&
        Objects.equals(this.bseSymbol, openapiHoldingDetailsData.bseSymbol) &&
        Objects.equals(this.bseTickSize, openapiHoldingDetailsData.bseTickSize) &&
        Objects.equals(this.cagr, openapiHoldingDetailsData.cagr) &&
        Objects.equals(this.collateral, openapiHoldingDetailsData.collateral) &&
        Objects.equals(this.collateralPerc, openapiHoldingDetailsData.collateralPerc) &&
        Objects.equals(this.collateralQty, openapiHoldingDetailsData.collateralQty) &&
        Objects.equals(this.collateralQtyCom, openapiHoldingDetailsData.collateralQtyCom) &&
        Objects.equals(this.collateralQtyCur, openapiHoldingDetailsData.collateralQtyCur) &&
        Objects.equals(this.collateralQtyDrv, openapiHoldingDetailsData.collateralQtyDrv) &&
        Objects.equals(this.comCollateral, openapiHoldingDetailsData.comCollateral) &&
        Objects.equals(this.costPrice, openapiHoldingDetailsData.costPrice) &&
        Objects.equals(this.curCollateral, openapiHoldingDetailsData.curCollateral) &&
        Objects.equals(this.displayName, openapiHoldingDetailsData.displayName) &&
        Objects.equals(this.drvCollateral, openapiHoldingDetailsData.drvCollateral) &&
        Objects.equals(this.exchange, openapiHoldingDetailsData.exchange) &&
        Objects.equals(this.exchangeInstName, openapiHoldingDetailsData.exchangeInstName) &&
        Objects.equals(this.isinCode, openapiHoldingDetailsData.isinCode) &&
        Objects.equals(this.lastTradedPrice, openapiHoldingDetailsData.lastTradedPrice) &&
        Objects.equals(this.marketValue, openapiHoldingDetailsData.marketValue) &&
        Objects.equals(this.nseSecurityId, openapiHoldingDetailsData.nseSecurityId) &&
        Objects.equals(this.nseSymbol, openapiHoldingDetailsData.nseSymbol) &&
        Objects.equals(this.nseTickSize, openapiHoldingDetailsData.nseTickSize) &&
        Objects.equals(this.pledgeQty, openapiHoldingDetailsData.pledgeQty) &&
        Objects.equals(this.previousClosePrice, openapiHoldingDetailsData.previousClosePrice) &&
        Objects.equals(this.quantity, openapiHoldingDetailsData.quantity) &&
        Objects.equals(this.remainingQuantity, openapiHoldingDetailsData.remainingQuantity) &&
        Objects.equals(this.rowNo, openapiHoldingDetailsData.rowNo) &&
        Objects.equals(this.securitySourceType, openapiHoldingDetailsData.securitySourceType) &&
        Objects.equals(this.totalQuantity, openapiHoldingDetailsData.totalQuantity) &&
        Objects.equals(this.utilizedQuantity, openapiHoldingDetailsData.utilizedQuantity) &&
        Objects.equals(this.xirr, openapiHoldingDetailsData.xirr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bseSecurityId, bseSymbol, bseTickSize, cagr, collateral, collateralPerc, collateralQty, collateralQtyCom, collateralQtyCur, collateralQtyDrv, comCollateral, costPrice, curCollateral, displayName, drvCollateral, exchange, exchangeInstName, isinCode, lastTradedPrice, marketValue, nseSecurityId, nseSymbol, nseTickSize, pledgeQty, previousClosePrice, quantity, remainingQuantity, rowNo, securitySourceType, totalQuantity, utilizedQuantity, xirr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiHoldingDetailsData {\n");
    
    sb.append("    bseSecurityId: ").append(toIndentedString(bseSecurityId)).append("\n");
    sb.append("    bseSymbol: ").append(toIndentedString(bseSymbol)).append("\n");
    sb.append("    bseTickSize: ").append(toIndentedString(bseTickSize)).append("\n");
    sb.append("    cagr: ").append(toIndentedString(cagr)).append("\n");
    sb.append("    collateral: ").append(toIndentedString(collateral)).append("\n");
    sb.append("    collateralPerc: ").append(toIndentedString(collateralPerc)).append("\n");
    sb.append("    collateralQty: ").append(toIndentedString(collateralQty)).append("\n");
    sb.append("    collateralQtyCom: ").append(toIndentedString(collateralQtyCom)).append("\n");
    sb.append("    collateralQtyCur: ").append(toIndentedString(collateralQtyCur)).append("\n");
    sb.append("    collateralQtyDrv: ").append(toIndentedString(collateralQtyDrv)).append("\n");
    sb.append("    comCollateral: ").append(toIndentedString(comCollateral)).append("\n");
    sb.append("    costPrice: ").append(toIndentedString(costPrice)).append("\n");
    sb.append("    curCollateral: ").append(toIndentedString(curCollateral)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    drvCollateral: ").append(toIndentedString(drvCollateral)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeInstName: ").append(toIndentedString(exchangeInstName)).append("\n");
    sb.append("    isinCode: ").append(toIndentedString(isinCode)).append("\n");
    sb.append("    lastTradedPrice: ").append(toIndentedString(lastTradedPrice)).append("\n");
    sb.append("    marketValue: ").append(toIndentedString(marketValue)).append("\n");
    sb.append("    nseSecurityId: ").append(toIndentedString(nseSecurityId)).append("\n");
    sb.append("    nseSymbol: ").append(toIndentedString(nseSymbol)).append("\n");
    sb.append("    nseTickSize: ").append(toIndentedString(nseTickSize)).append("\n");
    sb.append("    pledgeQty: ").append(toIndentedString(pledgeQty)).append("\n");
    sb.append("    previousClosePrice: ").append(toIndentedString(previousClosePrice)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    remainingQuantity: ").append(toIndentedString(remainingQuantity)).append("\n");
    sb.append("    rowNo: ").append(toIndentedString(rowNo)).append("\n");
    sb.append("    securitySourceType: ").append(toIndentedString(securitySourceType)).append("\n");
    sb.append("    totalQuantity: ").append(toIndentedString(totalQuantity)).append("\n");
    sb.append("    utilizedQuantity: ").append(toIndentedString(utilizedQuantity)).append("\n");
    sb.append("    xirr: ").append(toIndentedString(xirr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
