/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OpenapiOpenapiOrderModifyData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OpenapiOpenapiOrderModifyPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiOpenapiOrderModifyPayload {
  @SerializedName("data")
  private OpenapiOpenapiOrderModifyData data = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("token_id")
  private String tokenId = null;

  public OpenapiOpenapiOrderModifyPayload data(OpenapiOpenapiOrderModifyData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public OpenapiOpenapiOrderModifyData getData() {
    return data;
  }

  public void setData(OpenapiOpenapiOrderModifyData data) {
    this.data = data;
  }

  public OpenapiOpenapiOrderModifyPayload source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public OpenapiOpenapiOrderModifyPayload tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @Schema(description = "")
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiOpenapiOrderModifyPayload openapiOpenapiOrderModifyPayload = (OpenapiOpenapiOrderModifyPayload) o;
    return Objects.equals(this.data, openapiOpenapiOrderModifyPayload.data) &&
        Objects.equals(this.source, openapiOpenapiOrderModifyPayload.source) &&
        Objects.equals(this.tokenId, openapiOpenapiOrderModifyPayload.tokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, source, tokenId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiOpenapiOrderModifyPayload {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
