/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OpenapiUpdatePayOutDataPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiUpdatePayOutDataPayload {
  @SerializedName("ISIN_id")
  private String isINId = null;

  public OpenapiUpdatePayOutDataPayload isINId(String isINId) {
    this.isINId = isINId;
    return this;
  }

   /**
   * Get isINId
   * @return isINId
  **/
  @Schema(description = "")
  public String getIsINId() {
    return isINId;
  }

  public void setIsINId(String isINId) {
    this.isINId = isINId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiUpdatePayOutDataPayload openapiUpdatePayOutDataPayload = (OpenapiUpdatePayOutDataPayload) o;
    return Objects.equals(this.isINId, openapiUpdatePayOutDataPayload.isINId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isINId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiUpdatePayOutDataPayload {\n");
    
    sb.append("    isINId: ").append(toIndentedString(isINId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
