/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OpenapiOpenapiOrderEntryData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-30T23:12:44.291983900+05:30[Asia/Calcutta]")

public class OpenapiOpenapiOrderEntryData {
  @SerializedName("disc_quantity")
  private String discQuantity = null;

  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("group_id")
  private String groupId = null;

  @SerializedName("mkt_type")
  private String mktType = null;

  @SerializedName("off_mkt_flag")
  private String offMktFlag = null;

  @SerializedName("order_type")
  private String orderType = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("quantity")
  private String quantity = null;

  @SerializedName("remarks")
  private String remarks = null;

  @SerializedName("security_id")
  private String securityId = null;

  @SerializedName("segment")
  private String segment = null;

  @SerializedName("settlor")
  private String settlor = null;

  @SerializedName("trigger_price")
  private String triggerPrice = null;

  @SerializedName("txn_type")
  private String txnType = null;

  @SerializedName("validity")
  private String validity = null;

  public OpenapiOpenapiOrderEntryData discQuantity(String discQuantity) {
    this.discQuantity = discQuantity;
    return this;
  }

   /**
   * Get discQuantity
   * @return discQuantity
  **/
  @Schema(description = "")
  public String getDiscQuantity() {
    return discQuantity;
  }

  public void setDiscQuantity(String discQuantity) {
    this.discQuantity = discQuantity;
  }

  public OpenapiOpenapiOrderEntryData exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public OpenapiOpenapiOrderEntryData groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @Schema(description = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public OpenapiOpenapiOrderEntryData mktType(String mktType) {
    this.mktType = mktType;
    return this;
  }

   /**
   * Get mktType
   * @return mktType
  **/
  @Schema(description = "")
  public String getMktType() {
    return mktType;
  }

  public void setMktType(String mktType) {
    this.mktType = mktType;
  }

  public OpenapiOpenapiOrderEntryData offMktFlag(String offMktFlag) {
    this.offMktFlag = offMktFlag;
    return this;
  }

   /**
   * Get offMktFlag
   * @return offMktFlag
  **/
  @Schema(description = "")
  public String getOffMktFlag() {
    return offMktFlag;
  }

  public void setOffMktFlag(String offMktFlag) {
    this.offMktFlag = offMktFlag;
  }

  public OpenapiOpenapiOrderEntryData orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @Schema(description = "")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public OpenapiOpenapiOrderEntryData price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public OpenapiOpenapiOrderEntryData product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @Schema(description = "")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public OpenapiOpenapiOrderEntryData quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  public OpenapiOpenapiOrderEntryData remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * Get remarks
   * @return remarks
  **/
  @Schema(description = "")
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public OpenapiOpenapiOrderEntryData securityId(String securityId) {
    this.securityId = securityId;
    return this;
  }

   /**
   * Get securityId
   * @return securityId
  **/
  @Schema(description = "")
  public String getSecurityId() {
    return securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public OpenapiOpenapiOrderEntryData segment(String segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @Schema(description = "")
  public String getSegment() {
    return segment;
  }

  public void setSegment(String segment) {
    this.segment = segment;
  }

  public OpenapiOpenapiOrderEntryData settlor(String settlor) {
    this.settlor = settlor;
    return this;
  }

   /**
   * Get settlor
   * @return settlor
  **/
  @Schema(description = "")
  public String getSettlor() {
    return settlor;
  }

  public void setSettlor(String settlor) {
    this.settlor = settlor;
  }

  public OpenapiOpenapiOrderEntryData triggerPrice(String triggerPrice) {
    this.triggerPrice = triggerPrice;
    return this;
  }

   /**
   * Get triggerPrice
   * @return triggerPrice
  **/
  @Schema(description = "")
  public String getTriggerPrice() {
    return triggerPrice;
  }

  public void setTriggerPrice(String triggerPrice) {
    this.triggerPrice = triggerPrice;
  }

  public OpenapiOpenapiOrderEntryData txnType(String txnType) {
    this.txnType = txnType;
    return this;
  }

   /**
   * Get txnType
   * @return txnType
  **/
  @Schema(description = "")
  public String getTxnType() {
    return txnType;
  }

  public void setTxnType(String txnType) {
    this.txnType = txnType;
  }

  public OpenapiOpenapiOrderEntryData validity(String validity) {
    this.validity = validity;
    return this;
  }

   /**
   * Get validity
   * @return validity
  **/
  @Schema(description = "")
  public String getValidity() {
    return validity;
  }

  public void setValidity(String validity) {
    this.validity = validity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenapiOpenapiOrderEntryData openapiOpenapiOrderEntryData = (OpenapiOpenapiOrderEntryData) o;
    return Objects.equals(this.discQuantity, openapiOpenapiOrderEntryData.discQuantity) &&
        Objects.equals(this.exchange, openapiOpenapiOrderEntryData.exchange) &&
        Objects.equals(this.groupId, openapiOpenapiOrderEntryData.groupId) &&
        Objects.equals(this.mktType, openapiOpenapiOrderEntryData.mktType) &&
        Objects.equals(this.offMktFlag, openapiOpenapiOrderEntryData.offMktFlag) &&
        Objects.equals(this.orderType, openapiOpenapiOrderEntryData.orderType) &&
        Objects.equals(this.price, openapiOpenapiOrderEntryData.price) &&
        Objects.equals(this.product, openapiOpenapiOrderEntryData.product) &&
        Objects.equals(this.quantity, openapiOpenapiOrderEntryData.quantity) &&
        Objects.equals(this.remarks, openapiOpenapiOrderEntryData.remarks) &&
        Objects.equals(this.securityId, openapiOpenapiOrderEntryData.securityId) &&
        Objects.equals(this.segment, openapiOpenapiOrderEntryData.segment) &&
        Objects.equals(this.settlor, openapiOpenapiOrderEntryData.settlor) &&
        Objects.equals(this.triggerPrice, openapiOpenapiOrderEntryData.triggerPrice) &&
        Objects.equals(this.txnType, openapiOpenapiOrderEntryData.txnType) &&
        Objects.equals(this.validity, openapiOpenapiOrderEntryData.validity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discQuantity, exchange, groupId, mktType, offMktFlag, orderType, price, product, quantity, remarks, securityId, segment, settlor, triggerPrice, txnType, validity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenapiOpenapiOrderEntryData {\n");
    
    sb.append("    discQuantity: ").append(toIndentedString(discQuantity)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    mktType: ").append(toIndentedString(mktType)).append("\n");
    sb.append("    offMktFlag: ").append(toIndentedString(offMktFlag)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    settlor: ").append(toIndentedString(settlor)).append("\n");
    sb.append("    triggerPrice: ").append(toIndentedString(triggerPrice)).append("\n");
    sb.append("    txnType: ").append(toIndentedString(txnType)).append("\n");
    sb.append("    validity: ").append(toIndentedString(validity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
