/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.OpenapiOpenAPIErrorResponse;
import io.swagger.client.model.OpenapiOpenApiHoldingDetailsResponse;
import io.swagger.client.model.OpenapiOpenapiCommonReq;
import io.swagger.client.model.OpenapiOpenapiResponse;
import io.swagger.client.model.OpenapiOpenapiUpdatePayOutPayload;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for HoldingsApi
 */
@Ignore
public class HoldingsApiTest {

    private final HoldingsApi api = new HoldingsApi();

    /**
     * Holdings holdings.
     *
     * The API retrieves the user&#x27;s long-term holdings, kept in the DEMAT account until sold, removed from the exchange, or changed by stock exchange rules, ensuring regulatory compliance.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV1HoldingsPostTest() throws Exception {
        OpenapiOpenapiCommonReq body = null;
        OpenapiOpenApiHoldingDetailsResponse response = api.apiV1HoldingsPost(body);

        // TODO: test validations
    }
    /**
     * UpdatePayOut holdings.
     *
     * The Holding Update PayOut API endpoint processes a request to update payout details for a specified holding by ISIN ID, and it returns the updated holding quantities and status. This ensures accurate tracking of holding quantities post-update.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV1HoldingsUpdatePayoutPostTest() throws Exception {
        OpenapiOpenapiUpdatePayOutPayload body = null;
        OpenapiOpenapiResponse response = api.apiV1HoldingsUpdatePayoutPost(body);

        // TODO: test validations
    }
}
