/*
 * Torus Open API
 * This is the API documentation for Torus Open API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.OpenapiOpenAPIErrorResponse;
import io.swagger.client.model.OpenapiOpenApiTradeBookResponse;
import io.swagger.client.model.OpenapiOpenapiCommonReq;
import io.swagger.client.model.OpenapiOpenapiOrderDetailPayload;
import io.swagger.client.model.OpenapiOpenapiOrderDetailsResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TradeApi
 */
@Ignore
public class TradeApiTest {

    private final TradeApi api = new TradeApi();

    /**
     * TradeBook trade.
     *
     * This API endpoint Retrieves the complete trade book/ledger for a client&#x27;s trading account. Provides a comprehensive record of all trades executed, including order details, product information, prices, quantities, timestamps, and other relevant trade data for auditing and regulatory compliance purposes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV1TradeBookPostTest() throws Exception {
        OpenapiOpenapiCommonReq body = null;
        OpenapiOpenApiTradeBookResponse response = api.apiV1TradeBookPost(body);

        // TODO: test validations
    }
    /**
     * TradeDetails trade.
     *
     * This API endpoint Retrieves the trade details and transaction history for a client&#x27;s trading account. Provides access to information about executed trades, including order details, product information, trade prices, quantities, and timestamps for monitoring and record-keeping purposes
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV1TradeDetailsPostTest() throws Exception {
        OpenapiOpenapiOrderDetailPayload body = null;
        OpenapiOpenapiOrderDetailsResponse response = api.apiV1TradeDetailsPost(body);

        // TODO: test validations
    }
}
